version: '3.8'

services:
  book-management-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/bookdb
    networks:
      - backend-network

  mongo:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - backend-network

volumes:
  mongodb_data_container:

networks:
  backend-network:
    external: true
